title: The Salt-Box
description: More Fidgety Than Expected
baseurl: "" # Set to "" for user/organization site, "/repo-name" for project site
url: "https://jbj-ph.github.io"

theme: minima
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"


